-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bit_reverse_accel is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    s_axis_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    s_axis_TVALID : IN STD_LOGIC;
    s_axis_TREADY : OUT STD_LOGIC;
    s_axis_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    s_axis_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    s_axis_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axis_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axis_TVALID : OUT STD_LOGIC;
    m_axis_TREADY : IN STD_LOGIC;
    m_axis_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axis_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axis_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of bit_reverse_accel is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "bit_reverse_accel_bit_reverse_accel,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-3,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=2.000000,HLS_SYN_LAT=4,HLS_SYN_TPT=4,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=5,HLS_SYN_LUT=74,HLS_VERSION=2023_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";

    signal ap_rst_n_inv : STD_LOGIC;
    signal s_axis_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal m_axis_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal regslice_both_m_axis_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state5_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal ap_block_state3_pp0_stage2_iter0 : BOOLEAN;
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal ap_block_state4_pp0_stage3_iter0 : BOOLEAN;
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_block_pp0_stage1_01001 : BOOLEAN;
    signal ap_block_pp0_stage2_01001 : BOOLEAN;
    signal ap_block_pp0_stage3_01001 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_s_axis_V_data_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal s_axis_TVALID_int_regslice : STD_LOGIC;
    signal s_axis_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_s_axis_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_s_axis_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_s_axis_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_V_last_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_s_axis_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_V_last_V_U_ack_in : STD_LOGIC;
    signal m_axis_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal m_axis_TVALID_int_regslice : STD_LOGIC;
    signal m_axis_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_m_axis_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal m_axis_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_m_axis_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal m_axis_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_m_axis_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_V_last_V_U_apdone_blk : STD_LOGIC;
    signal m_axis_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_m_axis_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component bit_reverse_accel_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_s_axis_V_data_V_U : component bit_reverse_accel_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_TDATA,
        vld_in => s_axis_TVALID,
        ack_in => regslice_both_s_axis_V_data_V_U_ack_in,
        data_out => s_axis_TDATA_int_regslice,
        vld_out => s_axis_TVALID_int_regslice,
        ack_out => s_axis_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_V_data_V_U_apdone_blk);

    regslice_both_s_axis_V_keep_V_U : component bit_reverse_accel_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_TKEEP,
        vld_in => s_axis_TVALID,
        ack_in => regslice_both_s_axis_V_keep_V_U_ack_in,
        data_out => s_axis_TKEEP_int_regslice,
        vld_out => regslice_both_s_axis_V_keep_V_U_vld_out,
        ack_out => s_axis_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_V_keep_V_U_apdone_blk);

    regslice_both_s_axis_V_strb_V_U : component bit_reverse_accel_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_TSTRB,
        vld_in => s_axis_TVALID,
        ack_in => regslice_both_s_axis_V_strb_V_U_ack_in,
        data_out => s_axis_TSTRB_int_regslice,
        vld_out => regslice_both_s_axis_V_strb_V_U_vld_out,
        ack_out => s_axis_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_V_strb_V_U_apdone_blk);

    regslice_both_s_axis_V_last_V_U : component bit_reverse_accel_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_TLAST,
        vld_in => s_axis_TVALID,
        ack_in => regslice_both_s_axis_V_last_V_U_ack_in,
        data_out => s_axis_TLAST_int_regslice,
        vld_out => regslice_both_s_axis_V_last_V_U_vld_out,
        ack_out => s_axis_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_V_last_V_U_apdone_blk);

    regslice_both_m_axis_V_data_V_U : component bit_reverse_accel_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => m_axis_TDATA_int_regslice,
        vld_in => m_axis_TVALID_int_regslice,
        ack_in => m_axis_TREADY_int_regslice,
        data_out => m_axis_TDATA,
        vld_out => regslice_both_m_axis_V_data_V_U_vld_out,
        ack_out => m_axis_TREADY,
        apdone_blk => regslice_both_m_axis_V_data_V_U_apdone_blk);

    regslice_both_m_axis_V_keep_V_U : component bit_reverse_accel_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => m_axis_TKEEP_int_regslice,
        vld_in => m_axis_TVALID_int_regslice,
        ack_in => regslice_both_m_axis_V_keep_V_U_ack_in_dummy,
        data_out => m_axis_TKEEP,
        vld_out => regslice_both_m_axis_V_keep_V_U_vld_out,
        ack_out => m_axis_TREADY,
        apdone_blk => regslice_both_m_axis_V_keep_V_U_apdone_blk);

    regslice_both_m_axis_V_strb_V_U : component bit_reverse_accel_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => m_axis_TSTRB_int_regslice,
        vld_in => m_axis_TVALID_int_regslice,
        ack_in => regslice_both_m_axis_V_strb_V_U_ack_in_dummy,
        data_out => m_axis_TSTRB,
        vld_out => regslice_both_m_axis_V_strb_V_U_vld_out,
        ack_out => m_axis_TREADY,
        apdone_blk => regslice_both_m_axis_V_strb_V_U_apdone_blk);

    regslice_both_m_axis_V_last_V_U : component bit_reverse_accel_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => m_axis_TLAST_int_regslice,
        vld_in => m_axis_TVALID_int_regslice,
        ack_in => regslice_both_m_axis_V_last_V_U_ack_in_dummy,
        data_out => m_axis_TLAST,
        vld_out => regslice_both_m_axis_V_last_V_U_vld_out,
        ack_out => m_axis_TREADY,
        apdone_blk => regslice_both_m_axis_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage3_subdone, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0, ap_block_pp0_stage1_subdone, ap_block_pp0_stage2_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_reset_idle_pp0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_reset_idle_pp0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state1_pp0_stage0_iter0, ap_block_state5_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter1)) or ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state1_pp0_stage0_iter0, ap_block_state5_pp0_stage0_iter1, m_axis_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter1) or (m_axis_TREADY_int_regslice = ap_const_logic_0))) or ((ap_const_logic_1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or (m_axis_TREADY_int_regslice = ap_const_logic_0))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state1_pp0_stage0_iter0, ap_block_state5_pp0_stage0_iter1, m_axis_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter1) or (m_axis_TREADY_int_regslice = ap_const_logic_0))) or ((ap_const_logic_1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or (m_axis_TREADY_int_regslice = ap_const_logic_0))));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_01001_assign_proc : process(ap_block_state2_pp0_stage1_iter0)
    begin
                ap_block_pp0_stage1_01001 <= ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0));
    end process;


    ap_block_pp0_stage1_11001_assign_proc : process(ap_block_state2_pp0_stage1_iter0, m_axis_TREADY_int_regslice)
    begin
                ap_block_pp0_stage1_11001 <= ((ap_const_logic_1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0) or (m_axis_TREADY_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage1_subdone_assign_proc : process(ap_block_state2_pp0_stage1_iter0, m_axis_TREADY_int_regslice)
    begin
                ap_block_pp0_stage1_subdone <= ((ap_const_logic_1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0) or (m_axis_TREADY_int_regslice = ap_const_logic_0)));
    end process;

        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_01001_assign_proc : process(ap_block_state3_pp0_stage2_iter0)
    begin
                ap_block_pp0_stage2_01001 <= ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0));
    end process;


    ap_block_pp0_stage2_11001_assign_proc : process(ap_block_state3_pp0_stage2_iter0, m_axis_TREADY_int_regslice)
    begin
                ap_block_pp0_stage2_11001 <= ((ap_const_logic_1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0) or (m_axis_TREADY_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage2_subdone_assign_proc : process(ap_block_state3_pp0_stage2_iter0, m_axis_TREADY_int_regslice)
    begin
                ap_block_pp0_stage2_subdone <= ((ap_const_logic_1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0) or (m_axis_TREADY_int_regslice = ap_const_logic_0)));
    end process;

        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_01001_assign_proc : process(ap_block_state4_pp0_stage3_iter0)
    begin
                ap_block_pp0_stage3_01001 <= ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage3_iter0));
    end process;


    ap_block_pp0_stage3_11001_assign_proc : process(ap_block_state4_pp0_stage3_iter0, m_axis_TREADY_int_regslice)
    begin
                ap_block_pp0_stage3_11001 <= ((ap_const_logic_1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state4_pp0_stage3_iter0) or (m_axis_TREADY_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage3_subdone_assign_proc : process(ap_block_state4_pp0_stage3_iter0, m_axis_TREADY_int_regslice)
    begin
                ap_block_pp0_stage3_subdone <= ((ap_const_logic_1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state4_pp0_stage3_iter0) or (m_axis_TREADY_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(s_axis_TVALID_int_regslice, m_axis_TREADY_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((m_axis_TREADY_int_regslice = ap_const_logic_0) or (s_axis_TVALID_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage1_iter0_assign_proc : process(s_axis_TVALID_int_regslice, m_axis_TREADY_int_regslice)
    begin
                ap_block_state2_pp0_stage1_iter0 <= ((m_axis_TREADY_int_regslice = ap_const_logic_0) or (s_axis_TVALID_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage2_iter0_assign_proc : process(s_axis_TVALID_int_regslice, m_axis_TREADY_int_regslice)
    begin
                ap_block_state3_pp0_stage2_iter0 <= ((m_axis_TREADY_int_regslice = ap_const_logic_0) or (s_axis_TVALID_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state4_pp0_stage3_iter0_assign_proc : process(s_axis_TVALID_int_regslice, m_axis_TREADY_int_regslice)
    begin
                ap_block_state4_pp0_stage3_iter0 <= ((m_axis_TREADY_int_regslice = ap_const_logic_0) or (s_axis_TVALID_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state5_pp0_stage0_iter1_assign_proc : process(regslice_both_m_axis_V_data_V_U_apdone_blk, m_axis_TREADY_int_regslice)
    begin
                ap_block_state5_pp0_stage0_iter1 <= ((regslice_both_m_axis_V_data_V_U_apdone_blk = ap_const_logic_1) or (m_axis_TREADY_int_regslice = ap_const_logic_0));
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_reset_idle_pp0 <= ap_const_logic_0;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    m_axis_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3, ap_enable_reg_pp0_iter1, m_axis_TREADY_int_regslice)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            m_axis_TDATA_blk_n <= m_axis_TREADY_int_regslice;
        else 
            m_axis_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    
    m_axis_TDATA_int_regslice_proc : process(s_axis_TDATA_int_regslice)
    variable vlo_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable m_axis_TDATA_int_regslice_i : integer;
    variable section : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_1F(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        v0_cpy := s_axis_TDATA_int_regslice;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_1F(5-1 downto 0)));
            for m_axis_TDATA_int_regslice_i in 0 to 32-1 loop
                v0_cpy(m_axis_TDATA_int_regslice_i) := s_axis_TDATA_int_regslice(32-1-m_axis_TDATA_int_regslice_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(32-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        m_axis_TDATA_int_regslice <= resvalue(32-1 downto 0);
    end process;

    m_axis_TKEEP_int_regslice <= "XXXX";

    m_axis_TLAST_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage0_01001, ap_block_pp0_stage1_01001, ap_block_pp0_stage2_01001, ap_block_pp0_stage3_01001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_01001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            m_axis_TLAST_int_regslice <= ap_const_lv1_1;
        elsif ((((ap_const_boolean_0 = ap_block_pp0_stage2_01001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_01001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            m_axis_TLAST_int_regslice <= ap_const_lv1_0;
        else 
            m_axis_TLAST_int_regslice <= "X";
        end if; 
    end process;

    m_axis_TSTRB_int_regslice <= "XXXX";
    m_axis_TVALID <= regslice_both_m_axis_V_data_V_U_vld_out;

    m_axis_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            m_axis_TVALID_int_regslice <= ap_const_logic_1;
        else 
            m_axis_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    s_axis_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3, s_axis_TVALID_int_regslice)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            s_axis_TDATA_blk_n <= s_axis_TVALID_int_regslice;
        else 
            s_axis_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    s_axis_TREADY <= regslice_both_s_axis_V_data_V_U_ack_in;

    s_axis_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            s_axis_TREADY_int_regslice <= ap_const_logic_1;
        else 
            s_axis_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

end behav;
