#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Aug 29 14:35:02 CEST 2025
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_pipeline_blockdesign_func_synth -key {Post-Synthesis:sim_1:Functional:tb_pipeline_blockdesign} -tclbatch tb_pipeline_blockdesign.tcl -protoinst "protoinst_files/design_1.protoinst" -log simulate.log"
xsim tb_pipeline_blockdesign_func_synth -key {Post-Synthesis:sim_1:Functional:tb_pipeline_blockdesign} -tclbatch tb_pipeline_blockdesign.tcl -protoinst "protoinst_files/design_1.protoinst" -log simulate.log

