// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="bit_reverse_accel_bit_reverse_accel,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a200t-fbg676-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.994500,HLS_SYN_LAT=7,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=41,HLS_SYN_LUT=101,HLS_VERSION=2023_2}" *)

module bit_reverse_accel (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        s_axis_TVALID,
        m_axis_TREADY,
        s_axis_TDATA,
        s_axis_TREADY,
        s_axis_TKEEP,
        s_axis_TSTRB,
        s_axis_TLAST,
        m_axis_TDATA,
        m_axis_TVALID,
        m_axis_TKEEP,
        m_axis_TSTRB,
        m_axis_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   s_axis_TVALID;
input   m_axis_TREADY;
input  [31:0] s_axis_TDATA;
output   s_axis_TREADY;
input  [3:0] s_axis_TKEEP;
input  [3:0] s_axis_TSTRB;
input  [0:0] s_axis_TLAST;
output  [31:0] m_axis_TDATA;
output   m_axis_TVALID;
output  [3:0] m_axis_TKEEP;
output  [3:0] m_axis_TSTRB;
output  [0:0] m_axis_TLAST;

reg ap_idle;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln25_fu_114_p2;
reg    ap_block_state1_pp0_stage0_iter0;
wire    regslice_both_m_axis_V_data_V_U_apdone_blk;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state3_pp0_stage0_iter2;
wire    ap_loop_exit_ready;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
reg    ap_ready_int;
reg    s_axis_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    m_axis_TDATA_blk_n;
reg    ap_block_pp0_stage0_11001;
reg   [31:0] reversed_fu_130_p4;
reg   [31:0] reversed_reg_162;
wire   [0:0] output_word_last_fu_140_p2;
reg   [0:0] output_word_last_reg_167;
reg   [2:0] i_fu_72;
wire   [2:0] i_2_fu_120_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i_1;
reg    ap_block_pp0_stage0_01001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    regslice_both_s_axis_V_data_V_U_apdone_blk;
wire   [31:0] s_axis_TDATA_int_regslice;
wire    s_axis_TVALID_int_regslice;
reg    s_axis_TREADY_int_regslice;
wire    regslice_both_s_axis_V_data_V_U_ack_in;
wire    regslice_both_s_axis_V_keep_V_U_apdone_blk;
wire   [3:0] s_axis_TKEEP_int_regslice;
wire    regslice_both_s_axis_V_keep_V_U_vld_out;
wire    regslice_both_s_axis_V_keep_V_U_ack_in;
wire    regslice_both_s_axis_V_strb_V_U_apdone_blk;
wire   [3:0] s_axis_TSTRB_int_regslice;
wire    regslice_both_s_axis_V_strb_V_U_vld_out;
wire    regslice_both_s_axis_V_strb_V_U_ack_in;
wire    regslice_both_s_axis_V_last_V_U_apdone_blk;
wire   [0:0] s_axis_TLAST_int_regslice;
wire    regslice_both_s_axis_V_last_V_U_vld_out;
wire    regslice_both_s_axis_V_last_V_U_ack_in;
reg    m_axis_TVALID_int_regslice;
wire    m_axis_TREADY_int_regslice;
wire    regslice_both_m_axis_V_data_V_U_vld_out;
wire    regslice_both_m_axis_V_keep_V_U_apdone_blk;
wire   [3:0] m_axis_TKEEP_int_regslice;
wire    regslice_both_m_axis_V_keep_V_U_ack_in_dummy;
wire    regslice_both_m_axis_V_keep_V_U_vld_out;
wire    regslice_both_m_axis_V_strb_V_U_apdone_blk;
wire   [3:0] m_axis_TSTRB_int_regslice;
wire    regslice_both_m_axis_V_strb_V_U_ack_in_dummy;
wire    regslice_both_m_axis_V_strb_V_U_vld_out;
wire    regslice_both_m_axis_V_last_V_U_apdone_blk;
wire    regslice_both_m_axis_V_last_V_U_ack_in_dummy;
wire    regslice_both_m_axis_V_last_V_U_vld_out;
reg    ap_condition_121;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 i_fu_72 = 3'd0;
#0 ap_done_reg = 1'b0;
end

bit_reverse_accel_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

bit_reverse_accel_regslice_both #(
    .DataWidth( 32 ))
regslice_both_s_axis_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_TDATA),
    .vld_in(s_axis_TVALID),
    .ack_in(regslice_both_s_axis_V_data_V_U_ack_in),
    .data_out(s_axis_TDATA_int_regslice),
    .vld_out(s_axis_TVALID_int_regslice),
    .ack_out(s_axis_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_V_data_V_U_apdone_blk)
);

bit_reverse_accel_regslice_both #(
    .DataWidth( 4 ))
regslice_both_s_axis_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_TKEEP),
    .vld_in(s_axis_TVALID),
    .ack_in(regslice_both_s_axis_V_keep_V_U_ack_in),
    .data_out(s_axis_TKEEP_int_regslice),
    .vld_out(regslice_both_s_axis_V_keep_V_U_vld_out),
    .ack_out(s_axis_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_V_keep_V_U_apdone_blk)
);

bit_reverse_accel_regslice_both #(
    .DataWidth( 4 ))
regslice_both_s_axis_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_TSTRB),
    .vld_in(s_axis_TVALID),
    .ack_in(regslice_both_s_axis_V_strb_V_U_ack_in),
    .data_out(s_axis_TSTRB_int_regslice),
    .vld_out(regslice_both_s_axis_V_strb_V_U_vld_out),
    .ack_out(s_axis_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_V_strb_V_U_apdone_blk)
);

bit_reverse_accel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_TLAST),
    .vld_in(s_axis_TVALID),
    .ack_in(regslice_both_s_axis_V_last_V_U_ack_in),
    .data_out(s_axis_TLAST_int_regslice),
    .vld_out(regslice_both_s_axis_V_last_V_U_vld_out),
    .ack_out(s_axis_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_V_last_V_U_apdone_blk)
);

bit_reverse_accel_regslice_both #(
    .DataWidth( 32 ))
regslice_both_m_axis_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(reversed_reg_162),
    .vld_in(m_axis_TVALID_int_regslice),
    .ack_in(m_axis_TREADY_int_regslice),
    .data_out(m_axis_TDATA),
    .vld_out(regslice_both_m_axis_V_data_V_U_vld_out),
    .ack_out(m_axis_TREADY),
    .apdone_blk(regslice_both_m_axis_V_data_V_U_apdone_blk)
);

bit_reverse_accel_regslice_both #(
    .DataWidth( 4 ))
regslice_both_m_axis_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_TKEEP_int_regslice),
    .vld_in(m_axis_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_V_keep_V_U_ack_in_dummy),
    .data_out(m_axis_TKEEP),
    .vld_out(regslice_both_m_axis_V_keep_V_U_vld_out),
    .ack_out(m_axis_TREADY),
    .apdone_blk(regslice_both_m_axis_V_keep_V_U_apdone_blk)
);

bit_reverse_accel_regslice_both #(
    .DataWidth( 4 ))
regslice_both_m_axis_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_TSTRB_int_regslice),
    .vld_in(m_axis_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_V_strb_V_U_ack_in_dummy),
    .data_out(m_axis_TSTRB),
    .vld_out(regslice_both_m_axis_V_strb_V_U_vld_out),
    .ack_out(m_axis_TREADY),
    .apdone_blk(regslice_both_m_axis_V_strb_V_U_apdone_blk)
);

bit_reverse_accel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_word_last_reg_167),
    .vld_in(m_axis_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_V_last_V_U_ack_in_dummy),
    .data_out(m_axis_TLAST),
    .vld_out(regslice_both_m_axis_V_last_V_U_vld_out),
    .ack_out(m_axis_TREADY),
    .apdone_blk(regslice_both_m_axis_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_121)) begin
        if ((icmp_ln25_fu_114_p2 == 1'd0)) begin
            i_fu_72 <= i_2_fu_120_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_72 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        output_word_last_reg_167 <= output_word_last_fu_140_p2;
        reversed_reg_162 <= reversed_fu_130_p4;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln25_fu_114_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_72;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        m_axis_TDATA_blk_n = m_axis_TREADY_int_regslice;
    end else begin
        m_axis_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axis_TVALID_int_regslice = 1'b1;
    end else begin
        m_axis_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln25_fu_114_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_axis_TDATA_blk_n = s_axis_TVALID_int_regslice;
    end else begin
        s_axis_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_fu_114_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_axis_TREADY_int_regslice = 1'b1;
    end else begin
        s_axis_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (regslice_both_m_axis_V_data_V_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (regslice_both_m_axis_V_data_V_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((m_axis_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((m_axis_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_pp0_stage0_iter1))) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (regslice_both_m_axis_V_data_V_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((m_axis_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((m_axis_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_pp0_stage0_iter1))) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((icmp_ln25_fu_114_p2 == 1'd0) & (s_axis_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((regslice_both_m_axis_V_data_V_U_apdone_blk == 1'b1) | (m_axis_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (m_axis_TREADY_int_regslice == 1'b0);
end

always @ (*) begin
    ap_condition_121 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign i_2_fu_120_p2 = (ap_sig_allocacmp_i_1 + 3'd1);

assign icmp_ln25_fu_114_p2 = ((ap_sig_allocacmp_i_1 == 3'd4) ? 1'b1 : 1'b0);

assign m_axis_TKEEP_int_regslice = 'bx;

assign m_axis_TSTRB_int_regslice = 'bx;

assign m_axis_TVALID = regslice_both_m_axis_V_data_V_U_vld_out;

assign output_word_last_fu_140_p2 = ((ap_sig_allocacmp_i_1 == 3'd3) ? 1'b1 : 1'b0);

integer ap_tvar_int_0;

always @ (s_axis_TDATA_int_regslice) begin
    for (ap_tvar_int_0 = 32 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 31 - 0) begin
            reversed_fu_130_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            reversed_fu_130_p4[ap_tvar_int_0] = s_axis_TDATA_int_regslice[31 - ap_tvar_int_0];
        end
    end
end

assign s_axis_TREADY = regslice_both_s_axis_V_data_V_U_ack_in;


reg find_kernel_block = 0;
// synthesis translate_off
`include "bit_reverse_accel_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //bit_reverse_accel

